### ISSUE TITLE
User Interface (UI) design discussion thread

### ISSUE THREAD

**Issue by marceline-cramer** [mondradiko/mondradiko#6]
# Goals

Mondradiko's UI serves multiple purposes:

- To configure the user's local settings
- To allow users to interact with other users (e.g. friend requests, messaging, inviting, blocking, muting)
- To give the server a way of interacting with the client (server-defined menus, world maps, player inventory, HUDs, whatever else the server requires)

The primary goal of the UI system is to be as flexible and customizable as possible. Because users will be spending lots of time in the same client across multiple servers, they should be able to make their UI feel comfortable and homely. This may involve something as simple as a custom color scheme, to custom widget shapes, to a complete user interface overhaul with different interaction mechanics.

Additionally, it's essential that UI files, such as WebAssembly scripts, symbols, glyphs, sounds, vector images, etc., can be easily loaded, packaged, and distributed, so that people can share their UI implementations with other users.

Because Mondradiko is meant to be future-proof, and abstract away VR hardware for all clients, the UI framework must also be designed with hardware interoperability in mind. The same user UI implementation must instantly be compatible with hand tracking, handheld controllers, or whatever other kinds of input methods we support in the future.

# Implementation

Here is my proposal:

- All user interface widgets are positioned on a "Panel"
- Panels are rectangular, have a width and height, but can also curve inwards or outwards on either axis
- Panels have a specified background color, and can be transparent, composited over the rest of the VR world
- Panels are the only UI components that are visible from other clients, as blank rectangles with no widgets drawn over them
- UI layouts are defined in a DOM, specified in a markup format of some sort (probably [UIML](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=uiml))
- Each DOM component (Widget) is of a specific class (for example, button, slider, checkbox, radio button)
- Widgets are two-dimensional, and mapped onto the surface of a Panel
- The WebAssembly UI scripting environment exports callbacks for each Widget class (for example, on render, on click, on hover, etc.)
- Scripts are responsible for calling the engine's UI rendering API, which draws the shapes and glyphs of a widget onto a Panel
- Scripts are responsible for producing the necessary outputs for each widget (such as exporting float values from a slider, or booleans from a checkbox), so they effectively implement all of the interaction functionality

# Problems

If this proposal is agreed upon, there are several questions that need to be answered in this issue thread:

- What kinds of Widgets will we have?
- What UI drawing commands and available shapes should be available to the UI scripts?
- How will user interaction be handled, and built in such a way that it's friendly to both hand tracking and traditional VR controllers?
- How will Widgets be organized by the markup language onto a Panel?

Any thoughts or suggestions are appreciated!

**Comment by technobaboo** [comment]
I'd do better discussing this on voice chat, but for the moment I think 3D should be doable as well, bounded inside primitives. I also think there should be seperate panels for everything that can have their edges magnetically snap together. Other than that, I like a lot of this proposal.

**Comment by marceline-cramer** [comment]
> I'd do better discussing this on voice chat

Yeah, I agree that voice chat is better for designing engine features, but with a forum-like format like this, it's easier for other people to contribute to the discussion, and record it for later.

**Comment by korakoe** [comment]
Calories burnt widget? It would be cool to see how many calories you have burnt during the virtual day

**Comment by marceline-cramer** [comment]
> Calories burnt widget? It would be cool to see how many calories you have burnt during the virtual day

A service like that would be better provided by something like YUR, but there's no reason why we couldn't allow the client-side UI scripts to interact with various local services. Personally, I'd love to be able to control my Spotify player through a setup like that. Perhaps this could be done by exposing a client to services that could create menus and HUDs, like the server does? Those services, written in Python, for example, could then use the interaction from the user to do whatever a local Python script can do, such as fetching data from YUR, sending REST requests to Spotify, or even just playing music files locally.

Security-wise, the Mondradiko client would need to authorize various services to connect to the client's UI with IPC and create menus, but otherwise there's not much that could go wrong here, as the services would be running entirely client-side. The Panels spawned by the services would also be sent back to the server so that other clients can see that they exist, but that can't cause much of an issue either. It'd probably be fine if we just put a hard cap on the number of Panels that a client is allowed to spawn, so that they can't mess with other clients.

However, a system like this would be relatively low-priority, because it's a totally separate feature from "core" engine functionality. It'd also probably need to have an entire API binding written to talk to the client UI IPC, but I'm sure that @technobaboo has thoughts on how an application integration design like this would work.

**Comment by This-Is-Alex** [comment]
I really like your idea for the UI being constrained to a panel, where other users only see a panel but not the buttons on it.

I think designing a reusable UI framework would make having rich interactive experiences much easier to develop for.

I think there should be 3 "layers" of UI:
- UI-space: When a user opens their client-side UI, or another script causes a client-specific UI to open. This UI follows the player around when they move, and panels are placed on a sphere around the player (but individual panels are still rendered flat, not wrapping around the sphere)
- World-space: Everyone can see world-space UI elements. I envision this as an easy way to make a menu without having to place many scriptable objects for buttons and link them together. Depending on the individual components implemented this could even be expanded to allow a video to be played and the time synchronised between clients
- Screen-space: Non-interactable HUD that is anchored to a particular spot of your screen. VRChat does this nicely by showing a microphone indicator in the bottom left of your vision at all times. I think the placement of panels should be constrained to the borders of the screen (e.g. a script sets its position as "top" with "left" alignment), and the user should be able to customise the position of this box to accomodate for different FOV headsets.

**Comment by marceline-cramer** [comment]
I'm going to close this for now. We can re-open it later or start a GitHub Discussion board when we want to discuss more design.
